# Generated by Django 5.2.10 on 2026-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('en-US', 'English (US)'), ('pt-BR', 'Português (Brasil)'), ('fr-FR', 'Français'), ('ru-RU', 'Русский'), ('de-DE', 'Deutsch'), ('it-IT', 'Italiano'), ('zh-CN', '中文 (普通话)')], default='en-US', max_length=5),
        ),
    ]
